DROP SEQUENCE APP.CLIENT_SEQ RESTRICT;
DROP SEQUENCE APP.PROJECT_SEQ RESTRICT;
DROP SEQUENCE APP.PRODUCT_SEQ RESTRICT;
DROP SEQUENCE APP.UNIT_SEQ RESTRICT;
DROP SEQUENCE APP.FORMULA_SEQ RESTRICT;
DROP SEQUENCE APP.COMPONENT_SEQ RESTRICT;
DROP SEQUENCE APP.CATEGORY_SEQ RESTRICT;
DROP SEQUENCE APP.ASSEMBLY_SEQ RESTRICT;
DROP SEQUENCE APP.PARAMETER_SEQ RESTRICT;
DROP SEQUENCE APP.WORTH_SEQ RESTRICT;

create sequence APP.CLIENT_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.PROJECT_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.PRODUCT_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.UNIT_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.FORMULA_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.COMPONENT_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.CATEGORY_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.ASSEMBLY_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.PARAMETER_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
create sequence APP.WORTH_SEQ
AS BIGINT
INCREMENT BY 1
NO MAXVALUE;
